version: '3.8'

services:
    nginx:
        container_name: cv_app_nginx
        image: nginx:alpine
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel-network

    app:
        container_name: cv_app
        build: .
        depends_on:
            - db
        volumes:
            - ./:/var/www
        networks:
            - laravel-network


    db:
        container_name: cv_app_db
        image: mysql:8
        restart: always
        ports:
            - "3308:3306"
        environment:
            MYSQL_DATABASE: cv_app
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - cv_app_db:/var/lib/mysql
        networks:
            - laravel-network

    cv_app_node:
        container_name: cv_app_node
        image: node:20
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - laravel-network
        command: bash -c "npm install && npm run build"


networks:
    laravel-network:
        driver: bridge

volumes:
    cv_app_db: